#!/usr/bin/env python3
import os
import sys
import struct
import random
import string
from string import ascii_uppercase as l
from itertools import cycle, islice
from ctypes import c_ulong
from functools import reduce

# Repeats keystream to desired length
def rep(lst, m):
    return list(islice(cycle(lst), m))

def vdecrypt(keystream, ciphertext, message_file ):
  c = 0
  i = 0
  f = open(message_file, "wb")
  for c in range(len(ciphertext)):
    n = int.from_bytes(ciphertext[c], "big")
    i = int.from_bytes(keystream[c], "big")     
    v = n - i
    if (v < 0):
      v = v + 256
    f.write(v.to_bytes(1, 'big'))
  f.close()

key_blist = []
file = open(str(sys.argv[1]), 'rb')
while True:
  byte = file.read(1)
  if not byte:
    break
  key_blist.append(bytes(byte))
file.close()

ciphertext_blist = []
file2 = open(str(sys.argv[2]), 'rb')
while True:
  byte = file2.read(1)
  if not byte:
    break
  ciphertext_blist.append(bytes(byte))
file2.close()

keystream = rep(key_blist, len(ciphertext_blist) )
vdecrypt(keystream, ciphertext_blist, str(sys.argv[3]))

print("program complete!")

